#!/bin/sh

if [ "$1" != "start" ]; then
  exit 0
fi

echo "Starting g_ether module"

/sbin/modprobe ci_hdrc_imx
/sbin/modprobe g_ether use_eem=0 dev_addr=1a:55:89:a2:69:41 host_addr=1a:55:89:a2:69:42
